#+BLOG: blog.datalab.es
#+CATEGORY: 
#+TAGS: 
#+DESCRIPTION: Convocatoria de proyectos del quinto taller de producción de periodismo de datos
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+TITLE: V taller de producción de periodismo de datos, La España Vacía, convocatoria de proyectos
#+DATE: <2017-01-12 jue 16:00>
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+TOC: headlines 2
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \addto\captionsenglish{\renewcommand{\contentsname}{{\'I}ndice}}
#+LATEX_HEADER: \renewcommand{\contentsname}{Índice}
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Herramientas de Scraping de PDF y Web.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/
#+LATEX_HEADER: \maketitle
#+LATEX_HEADER: \tableofcontents

Desde el 2 de febrero y hasta el 5 de marzo de 2017 está abierta la convocatoria de proyectos para el V taller de producción de periodismo de datos, /La España vacía/. Los proyectos seleccionados se desarrollarán en el taller que contará con el asesoramiento de profesionales de medios de comunicación nacionales e internacionales y expertos en análisis, tratamiento y visualización de datos.

Esta convocatoria va dirigida a periodistas, programadores, desarrolladores front/back, diseñadores UX, estadísticos, visualizadores de datos y, en general, cualquier persona que quiera trabajar con datos para sacar historias de ellos, ya sean estudiantes, profesionales de alguna rama o simples personas curiosas.

La fecha límite para la presentación de proyectos es el domingo 5 de marzo a las 12 de la noche UTC+2. La inscripción es gratuíta.

#+CAPTION: Imagen de Miguel Ángel García. Ermita de nuestra Señora de Jerusalén
#+ATTR_HTML: :alt Imagen de Miguel Ángel García. Ermita de nuestra Señora de Jerusalén :title Nuestra Sra. de Jerusalén
https://farm6.staticflickr.com/5635/31400708025_f1c4f211c7_z_d.jpg

* Condiciones

Los proyectos deben reunir estas condiciones:

- Recopilación y análisis de datos para crear una historia o herramienta periodística.
- Fuentes de datos fiables y localizadas antes de la realización del taller.
- Tema relacionado con la narrativa del taller. Algunos ejemplos:
 - Flujos demográficos en el interior de España.
 - Flujos demográficos hacia España o desde España.
 - Ordenación del territorio: agricultura, ganadería, industria, energía, etc.
 - Movimientos de personas, mercancías o animales.
 - Diferencias zonas urbanas/rurales
 - Residuos
 - Contaminación

Los resultados y el código fuente deben tener licencias libres que permitan el acceso y la difusión del conocimiento producido durante el taller.

Si tienes cualquier duda, escribe a [[mailto:visualizar@medialab-prado.es][visualizar @ medialab-prado.es]]

¿Quieres apuntarte al taller simplemente para trabajar en uno de los proyectos? El 6 de marzo se abrirá la convocatoria de colaboradores en la web de Medialab-Prado.

* Presentación de proyectos

Este año tenéis que rellenar el formulario que aparece a continuación con todos vuestros datos. Sin embargo y como novedad, os proponemos dos cosas:

** Publicación previa del proyecto

La primera, que publiquéis vuestro proyecto en algún sitio web, como por ejemplo Github, Gitlab, bitbucket o cualquier otra web de gestión de proyectos que permita que más usuarixs puedan sumarse desde ya y de esta manera comencéis a trabajar incluso sin saber si vas a ser seleccionados.

En las dos últimas ediciones hemos utilizado Github para la gestión de los proyectos y de los equipos y queremos potenciar su uso y el trabajo en red y colaborativo. Además, de esta forma quizás consigáis que otras personas aporten sugerencias que hagan que vuestra propuesta sea mejor.

** Día de los datos abiertos
Si contáis con datos, ya sean muchos y pocos, o bien los tenéis localizados pero no habéis accedido a ellos, o pensáis que se pueden sacar de tal sitio pero no sabéis cómo, os proponemos que presentéis el proyecto al día de los datos abiertos que se celebra en [[http://madrid.opendataday.org][Madrid]] y otros lugares de [[http://spain.opendataday.org][España]] y del [[http://opendataday.org][mundo]] el sábado 4 de marzo. De esta manera, damos oportunidad a enriquecer las fuentes de datos del proyecto antes de su fecha límite de presentación el 5 de marzo.

* Fechas

- 2 febrero, publicación de convocatoria de proyectos
- 4 marzo, día de los datos abiertos.
- 5 marzo, fecha límite de presentación de propuestas.
- 6 marzo, publicación de convocatoria de colaboradorxs.
- 7 abril, fecha límite de convocatoria de colaboradorxs.
- 7, 8 y 9 abril, primera sesión.
- 5, 6 y 7 mayo, segunda sesión.
- 18, 19 y 20 junio, tercera sesión.

* Formulario
